import os
from pathlib import Path

from flask import Flask, jsonify, request, send_from_directory
from huggingface_hub import InferenceClient

from decode import parse_prediction, query_to_sql


BASE_DIR = Path(__file__).resolve().parent
UI_DIR = BASE_DIR / "UI"
MODEL_ID = "shaaf257/text-2-sql-scratch"

app = Flask(__name__)


def build_prompt(question, columns):
    column_tokens = " ".join(
        f"<c{index}> {column}"
        for index, column in enumerate(columns)
    )
    return f"{question.strip()} <sep> {column_tokens}".lower()


@app.get("/")
def landing_page():
    return send_from_directory(UI_DIR, "landing.html")


@app.get("/<path:filename>")
def ui_file(filename):
    return send_from_directory(UI_DIR, filename)


@app.post("/api/query")
def generate_query():
    payload = request.get_json(silent=True) or {}
    question = payload.get("question")
    columns = payload.get("columns")

    if not isinstance(question, str) or not question.strip():
        return jsonify({"error": "question is required"}), 400
    if not isinstance(columns, str) or not columns.strip():
        return jsonify({"error": "columns is required"}), 400

    header = [column.strip() for column in columns.split(",") if column.strip()]
    if not header:
        return jsonify({"error": "columns must contain at least one column"}), 400

    token = os.environ.get("HF_TOKEN")
    if not token:
        return jsonify({"error": "HF_TOKEN environment variable is not configured"}), 503

    try:
        client = InferenceClient(provider="hf-inference", api_key=token)
        generated = client.text_generation(
            model=MODEL_ID,
            prompt=build_prompt(question, header),
            max_new_tokens=100,
        )
        generated = generated.strip()
        parsed = parse_prediction(generated)
        sql = query_to_sql(parsed, header)
    except Exception as error:
        app.logger.exception("Hugging Face inference failed")
        return jsonify({"error": f"Inference failed: {error}"}), 502

    return jsonify(
        {
            "sql": sql or generated,
            "query": generated,
            "message": "Generated by Hugging Face inference",
        }
    )


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", "5000")))
