const configuredApi = new URLSearchParams(window.location.search).get("api");
const storedApi = window.localStorage.getItem("inferenceApiUrl");
const API_ENDPOINT = configuredApi || window.INFERENCE_API_URL || storedApi || "/api/query";

function normalizeApiEndpoint(value) {
  const url = new URL(value.trim());
  if (!["http:", "https:"].includes(url.protocol)) {
    throw new Error("Endpoint must use http:// or https://");
  }
  if (!url.pathname.endsWith("/api/query")) {
    url.pathname = `${url.pathname.replace(/\/$/, "")}/api/query`;
  }
  return url.toString();
}

function setupInferenceEndpoint() {
  const input = document.querySelector("#inference-endpoint");
  const saveButton = document.querySelector("#save-endpoint");
  const error = document.querySelector("#endpoint-error");
  if (!input || !saveButton) return;

  input.value = configuredApi || storedApi || "";
  saveButton.addEventListener("click", () => {
    try {
      const endpoint = normalizeApiEndpoint(input.value);
      window.localStorage.setItem("inferenceApiUrl", endpoint);
      input.value = endpoint;
      error.hidden = true;
      error.textContent = "";
    } catch (endpointError) {
      error.hidden = false;
      error.textContent = endpointError.message;
    }
  });

  document.querySelectorAll(".slide-link").forEach((link) => {
    link.addEventListener("click", (event) => {
      const endpoint = input.value.trim();
      if (!endpoint) {
        event.preventDefault();
        error.hidden = false;
        error.textContent = "Enter the inference endpoint before opening Query Studio.";
        input.focus();
        return;
      }
      try {
        const normalizedEndpoint = normalizeApiEndpoint(endpoint);
        window.localStorage.setItem("inferenceApiUrl", normalizedEndpoint);
        link.href = `query.html?api=${encodeURIComponent(normalizedEndpoint)}`;
        event.preventDefault();
        document.body.classList.add("page-exit");
        window.setTimeout(() => {
          window.location.href = link.href;
        }, 220);
      } catch (endpointError) {
        event.preventDefault();
        error.hidden = false;
        error.textContent = endpointError.message;
      }
    });
  });
}

function selectedStrategy() {
  return document.querySelector("input[name='strategy']:checked").value;
}

function setupDecoderControls() {
  const beamSetting = document.querySelector("#beam-setting");
  const beamSize = document.querySelector("#beam-size");
  const beamValue = document.querySelector("#beam-value");
  document.querySelectorAll("input[name='strategy']").forEach((radio) => {
    radio.addEventListener("change", () => {
      document.querySelectorAll(".choice-card").forEach((card) => {
        card.classList.toggle("selected", card.querySelector("input").checked);
      });
      const isBeam = selectedStrategy() === "beam";
      beamSetting.classList.toggle("visible", isBeam);
      beamSetting.setAttribute("aria-hidden", String(!isBeam));
    });
  });
  beamSize.addEventListener("input", () => {
    beamValue.value = beamSize.value;
    beamValue.textContent = beamSize.value;
  });
}

async function requestQuery(payload) {
  const response = await fetch(API_ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || `API returned ${response.status}`);
  return result;
}

function setupQuery() {
  const form = document.querySelector("#query-form");
  const responseCard = document.querySelector("#response-card");
  const output = document.querySelector("#sql-output code");
  const responseMeta = document.querySelector("#response-meta");
  const responseStatus = document.querySelector("#response-status");
  const resultTag = document.querySelector("#result-tag");
  const submitButton = form.querySelector("button[type='submit']");

  setupDecoderControls();
  form.addEventListener("submit", async (event) => {
    event.preventDefault();
    const payload = {
      question: document.querySelector("#question").value.trim(),
      columns: document.querySelector("#columns").value.trim(),
      strategy: selectedStrategy(),
      beam_size: Number(document.querySelector("#beam-size").value)
    };
    if (!payload.question) return;

    submitButton.disabled = true;
    submitButton.innerHTML = "GENERATING... <span>◌</span>";
    let result;
    try {
      result = await requestQuery(payload);
    } catch (error) {
      result = { error: error.message };
    }
    output.textContent = result.error || result.sql || result.query || "No SQL was returned.";
    responseMeta.textContent = `${payload.strategy.toUpperCase()} SEARCH${payload.strategy === "beam" ? ` / WIDTH ${payload.beam_size}` : ""}  ·  ${payload.columns}`;
    responseStatus.textContent = result.error || result.message || "Generated by connected model";
    resultTag.textContent = result.error ? "ERROR" : "MODEL OUTPUT";
    responseCard.hidden = false;
    responseCard.scrollIntoView({ behavior: "smooth", block: "start" });
    submitButton.disabled = false;
    submitButton.innerHTML = "GENERATE SQL <span>→</span>";
  });

  document.querySelector("#copy-button").addEventListener("click", async () => {
    await navigator.clipboard.writeText(output.textContent);
    document.querySelector("#copy-button").textContent = "COPIED!";
    window.setTimeout(() => { document.querySelector("#copy-button").textContent = "COPY SQL"; }, 1400);
  });
}

if (document.querySelector(".landing-page")) setupInferenceEndpoint();
if (document.querySelector(".query-page")) setupQuery();
